import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chaeikim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-blue-800 min-h-screen">
          <h1 className="text-3xl font-bold underline">Hello</h1>
        </section>

      </main>
    </div>
  )
}
